modLoader = "javafml"
loaderVersion = "[${forge_major_version},)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "thermal"
version = "${file.jarVersion}"
displayName = "Thermal Series"
updateJSONURL = "https://raw.github.com/cofh/version/main/thermal/update.json"
displayURL = "https://teamcofh.com/"
logoFile = "thermal_series.png"
itemIcon = "thermal:tinker_bench"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Parent mod for all Thermal modules.

Contains all of the common components for the Thermal Series, such as materials and basic tools.
'''
[[dependencies.thermal]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.1"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal]]
modId = "forge"
mandatory = true
versionRange = "[${neo_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal]]
modId = "cofh_core"
mandatory = true
versionRange = "${cofh_core_version_range}"
ordering = "AFTER"
side = "BOTH"
